spring.application.name=product-service
#Config Server location
spring.config.import=optional:configserver:http://localhost:8746

#server.port=8082
#
##Key for JWT
#jwt.secret=${JWT_SECRET}
#
## Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/shopzone_product?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=${SPRING_MYSQL_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA Configuration
#spring.jpa.hibernate.ddl-auto=validate
#spring.flyway.enabled=true
#logging.level.org.flywaydb=DEBUG
#spring.jpa.open-in-view = false
## Logging (Optional: to debug SQL statements and Hibernate behavior)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.tool.schema=DEBUG
#
##FILE UPLOAD
#file.uploadDir=uploads
#
## Eureka Location
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka


